### ISSUE TITLE
H5parm_collector unrecognized argument

### ISSUE THREAD

**Issue by alexmatze** [tikk3r/lofar-grid-hpccloud#12]
So I am testing the lofar singularity image. Adjusted all files as requested and started the Pre-Factor-Calibrator parset. Unfortunately H5parm_collector.py in losoto  complains about an argument "-q" that was given, not to know.:

```
2019-03-14 14:02:14 INFO    genericpipeline.executable_args: Waiting for compute threads...
2019-03-14 14:02:14 WARNING node.lonode001.executable_args.instrument.h5]: /opt/lofar/losoto/bin/H5parm_collector.py stderr: usage: H5parm_collector.py [-h] [--insolset INSOLSET] [--outsolset OUTSOLSET]
                           [--insoltab INSOLTAB] [--outh5parm OUTH5PARM]
                           [--verbose] [--clobber]
                           h5parmFiles [h5parmFiles ...]
H5parm_collector.py: error: unrecognized arguments: -q

2019-03-14 14:02:17 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('127.0.0.1', 57800)
2019-03-14 14:02:17 ERROR   node.lonode001.executable_args: Command '/opt/lofar/losoto/bin/H5parm_collector.py' returned non-zero exit status 2
2019-03-14 14:02:17 INFO    node.lonode001.executable_args: Total time 3.0061s; user time: 0.2320s; system time: 0.2000s
2019-03-14 14:02:17 DEBUG   node.lonode001.executable_args: Start time was 1552568534.5399s; end time was 1552568537.5461s

```

is that a known issue? I pulled the most recent version of prefactor btw

Cheers,
Alex

**Comment by alexmatze** [comment]
Another Issue that I encounter: I tried to remove the argument -q in the parset file, to see if it just runs through, now the next issue comes up with the following:
```

2019-03-14 14:38:54 - INFO: Plotting soltab: phase000
Traceback (most recent call last):
  File "/opt/lofar/losoto/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==2.0', 'losoto')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/opt/lofar/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/EGG-INFO/scripts/losoto", line 147, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/opt/lofar/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/plot.py", line 35, in _run_parser
    plotFlag, doUnwrap, refAnt, soltabsToAdd, makeAntPlot, makeMovie, prefix, ncpu)
  File "/opt/lofar/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/plot.py", line 353, in run
    mpm = multiprocManager(ncpu, _plot)
  File "/opt/lofar/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/lib_operations.py", line 50, in __init__
    self.inQueue = multiprocessing.JoinableQueue()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 225, in JoinableQueue
    return JoinableQueue(maxsize)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 298, in __init__
    Queue.__init__(self, maxsize)
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory

2019-03-14 14:38:57 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('127.0.0.1', 59148)
2019-03-14 14:38:57 ERROR   node.lonode001.executable_args: Command '/opt/lofar/losoto/bin/losoto' returned non-zero exit status 1
2019-03-14 14:38:57 INFO    node.lonode001.executable_args: Total time 4.0067s; user time: 0.3000s; system time: 0.7960s
2019-03-14 14:38:57 DEBUG   node.lonode001.executable_args: Start time was 1552570733.2883s; end time was 1552570737.2952s
2019-03-14 14:38:57 DEBUG   genericpipeline.executable_args: 

```
I don't think, this has something to do with the previous problem. It looks like it can not import the pkg_resources because they are not there?

**Comment by tikk3r** [comment]
Regarding the first problem: losoto had an update after the image was built, adding the `-q` option. The image needs to be rebuilt, and should be done later tonight if all goes well (or you can build it yourself).

Not sure about the second problem. I haven't encountered it yet.

**Comment by alexmatze** [comment]
Ok so now the first issue is solved. Still I run into the latter `one.__import__('pkg_resources').run_script('losoto==2.0', 'losoto')`

looks like there is no resource which it is trying to call at that step? 

2019-03-18 14:32:04 - DEBUG: Loading TEC module.
2019-03-18 14:32:04 - DEBUG: Loading TECJUMP module.
2019-03-18 14:32:04 - DEBUG: Appending to /scratch/WORK/tmp/Pre-Facet-Calibrator-0836/instrument.h5imp_cal_PA.
2019-03-18 14:32:04 - INFO: --> Starting 'plotP3' step (operation: PLOT).
2019-03-18 14:32:04 - DEBUG: Caching...
2019-03-18 14:32:04 - INFO: Plotting soltab: phase000

It looks like the plotting of solution tables is an issue? Do you know where I can inspect the packages, it tries to load for that step? Would check to load them manually.

**Comment by tikk3r** [comment]
Are you running with any special flags?

**Comment by alexmatze** [comment]
No I basically run the parset with only adjusted paths in the first block, to work with our data. Its also the most recent files from lofar-astron github.

**Comment by tikk3r** [comment]
Can you try `singularity shell <simg> --noprofile --norc` and then run it to eliminate (most of) the host stuff?

**Comment by alexmatze** [comment]
Same problem. 

also in the shell I get the following errors on opening the singularity shell:
```
/opt/lofar/init.sh: line 19: syntax error near unexpected token `('
/opt/lofar/init.sh: line 19: `if echo \$(hostname) | grep -qi na; then export DDF_PIPELINE_CLUSTER="paracluster"; else export DDF_PIPELINE_CLUSTER=; fi'
/opt/lofar/init.sh: line 19: syntax error near unexpected token `('
/opt/lofar/init.sh: line 19: `if echo \$(hostname) | grep -qi na; then export DDF_PIPELINE_CLUSTER="paracluster"; else export DDF_PIPELINE_CLUSTER=; fi'
```
As far as I remember this was not the case last week, so probably this is not causing any problems. so just as a remark at this point.

**Comment by tikk3r** [comment]
Yeah I'm aware of that, small bug that I added by mistake.
Not sure what file it doesn't find. You can try binding some of the temporary directories like `/tmp`.

**Comment by alexmatze** [comment]
binding /tmp change anything also. All other directories for working directory and so on are also bound. So when you run Pre-Facet-Calibrator with most recent files, it runs through without issues?

**Comment by tikk3r** [comment]
I have run it successfullly with this image yes. I don't do 3rd order tec however.

**Comment by alexmatze** [comment]
regarding the parset I use it should do only 1st order

**Comment by alexmatze** [comment]
Did you also run the test with the shell and noprofile and norc?

**Comment by tikk3r** [comment]
Oh yeah right, it's just plotting step 3, my bad. No I just run a plain `singularity exec <simg> genericpipeline.py -d -c pipeline.cfg <parset>`.

**Comment by alexmatze** [comment]
Maybe it was catching up something from your host so it could successfully complete on yours?

**Comment by tikk3r** [comment]
I don't think so. There's nothing installed on the cluster that it could pick up.

**Comment by alexmatze** [comment]
Good call! now it finished! Thanks
