### ISSUE TITLE
h5py/hdf5 installation broken

### ISSUE THREAD

**Issue by tikk3r** [tikk3r/lofar-grid-hpccloud#95]
**Describe the bug**
HDF5/h5py installation seems broken.

**To Reproduce**
Run e.g. boostrap in ddf pipeline.

**Expected behaviour**
A description of what you expected to happen.

**Logs or error messages**
```python
/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.4, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Traceback (most recent call last):
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 281, in <module>
    run_bootstrap(o)
  File "/opt/lofar/ddf-pipeline/scripts/bootstrap.py", line 189, in run_bootstrap
    fitting_factors.run_all(1, name=obsid)
  File "/opt/lofar/ddf-pipeline/utils/fitting_factors.py", line 93, in run_all
    import emcee
  File "/opt/lofar/pyenv-py3/lib/python3.11/site-packages/emcee/__init__.py", line 24, in <module>
    from . import autocorr, backends, moves
  File "/opt/lofar/pyenv-py3/lib/python3.11/site-packages/emcee/backends/__init__.py", line 4, in <module>
    from .hdf import HDFBackend, TempHDFBackend
  File "/opt/lofar/pyenv-py3/lib/python3.11/site-packages/emcee/backends/hdf.py", line 17, in <module>
    import h5py
  File "/opt/lofar/pyenv-py3/lib64/python3.11/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
  File "h5py/h5t.pyx", line 164, in init h5py.h5t
  File "h5py/h5t.pyx", line 83, in h5py.h5t.lockid
  File "h5py/h5t.pyx", line 52, in h5py.h5t.typewrap
ValueError: Not a datatype (not a datatype)
```

**Additional information (if applicable or known):**
5.3.0/5.3.1
Possibly related to https://github.com/h5py/h5py/issues/2436

**Comment by tikk3r** [comment]
Fixed in 5.3.1.
